[git/zsh] Update pre-commit hook.
This will not allow commits on develop, main or master.

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -3,19 +3,16 @@
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
 CONSOLE_DOT_LOG=$(rg 'console\.log')
 
-if [[ "$BRANCH" =~ ^(?:develop|master|main)$ ]]
-then
-    echo "You can't commit directly to $BRANCH branch"
-    exit 1
-elif [[ $(rg '(?:it|describe)\.only') ]]
-then
-    echo '"only" detected!'
-    exit 1
-elif [[ "$CONSOLE_DOT_LOG" ]]
-then
-    echo "'console-dot-log' found!"
-    echo "$CONSOLE_DOT_LOG"
-    exit 1
+if [[ "$BRANCH" =~ (develop|master|main) ]]; then
+	echo "You can't commit directly to $BRANCH"
+	exit 1
+elif [[ $(rg '(?:it|describe)\.only') ]]; then
+	echo '"only" detected!'
+	exit 1
+elif [[ "$CONSOLE_DOT_LOG" ]]; then
+	echo "'console-dot-log' found!"
+	echo "$CONSOLE_DOT_LOG"
+	exit 1
 fi
 
 # vim: ft=sh
